# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true

  matrix:
  - R_VERSION: stable

  - R_VERSION: patched

  - R_VERSION: oldrel
    RTOOLS_VERSION: 33

  - R_VERSION: devel

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
 - provider: Email
   to:
     - maelle.salmon@yahoo.se
   subject: 'geoparser build {{status}}'                  # optional
   message: "https://ci.appveyor.com/project/ropenscilabs/geoparser"    # optional
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true
